import { h } from '../lib/dom.js';

export function SiteHeader() {
  return h('header', { class: 'site-header' },
    h('div', { class: 'site-header__top' },
      h('div', { class: 'brand' },
        h('span', { class: 'brand__mark', 'aria-hidden': 'true' }, h('i'), h('i'), h('i')),
        h('span', { class: 'brand__name' }, 'context', h('strong', {}, '.ai'))),
      h('div', { class: 'site-header__status' },
        h('span', { class: 'status-dot', 'aria-hidden': 'true' }),
        'SIMULAÇÃO INTERATIVA')),
    h('div', { class: 'site-header__hero' },
      h('div', { class: 'site-header__copy' },
        h('p', { class: 'eyebrow' },
          h('span', { class: 'eyebrow__line', 'aria-hidden': 'true' }),
          'LABORATÓRIO DE CONTEXTO'),
        h('h1', {}, 'Uma pergunta. ', h('span', { class: 'grad' }, 'Duas respostas.')),
        h('p', { class: 'site-header__intro' }, 'Compare como a mesma IA responde quando recebe — ou não — as informações certas.'),
        h('div', { class: 'hero-actions' },
          h('a', { class: 'hero-cta', href: '#comparacao' },
            h('span', {}, 'Explorar a demonstração'),
            h('span', { class: 'hero-cta__arrow', 'aria-hidden': 'true' }, '↓')),
          h('span', { class: 'hero-actions__note' }, 'Troque as fontes e acompanhe o resultado.'))),
      h('aside', { class: 'hero-note', 'aria-label': 'Resumo da demonstração' },
        h('span', { class: 'hero-note__kicker' }, 'A IDEIA'),
        h('p', {}, 'Sem contexto, o modelo generaliza. Com contexto, conecta a resposta à sua situação.'),
        h('div', { class: 'hero-note__footer' },
          h('span', {}, 'MESMA PERGUNTA'),
          h('span', { class: 'hero-note__arrow', 'aria-hidden': 'true' }, '→'),
          h('span', {}, 'RESPOSTA MAIS ÚTIL')))));
}
